services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - PHP_HOST=${PHP_HOST}
      - PHP_PORT=${PHP_PORT}
      - CERTS_CRT=${CERTS_CRT}
      - CERTS_KEY=${CERTS_KEY}
      - ADMINER_HOST=${ADMINER_HOST}
      - ADMINER_PORT=${ADMINER_PORT}
      - STATIC_HOST=${STATIC_HOST}
      - STATIC_PORT=${STATIC_PORT}
      - KUMA_PORT=${KUMA_PORT}
      - KUMA_HOST=${KUMA_HOST}
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - web:/var/www/html
      - ../secrets/credentials.txt:/run/secrets/wp_credentials:ro
      - ../secrets/db_password.txt:/run/secrets/db_passwords:ro
    environment:
      - WP_EMAIL=${WP_EMAIL}
      - WP_TITLE=${WP_TITLE}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - PHP_HOST=${PHP_HOST}
      - PHP_PORT=${PHP_PORT}
    depends_on:
      - mariadb
    networks:
      - inception
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "php-fpm7.4 -t && kill -0 $(cat /run/php/php7.4-fpm.pid)"]
      interval: 10s
      timeout: 3s
      retries: 5

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
      - ../secrets/credentials.txt:/run/secrets/wp_credentials:ro
      - ../secrets/db_password.txt:/run/secrets/db_passwords:ro
      - ../secrets/db_root_password.txt:/run/secrets/db_root_password:ro
    networks:
      - inception
    restart: unless-stopped

  static:
    build:
      context: ./requirements/bonus/static
    container_name: static
    networks:
      - inception
    expose:
      - ${STATIC_PORT}
    restart: unless-stopped

  adminer:
    build:
      context: ./requirements/bonus/adminer
    container_name: adminer
    environment:
      - ADMINER_PORT=${ADMINER_PORT}
    networks:
      - inception
    expose:
      - ${ADMINER_PORT}
    restart: unless-stopped

  ftp:
    build:
      context: ./requirements/bonus/ftp
    volumes:
      - web:/var/www/html
      - ../secrets/credentials.txt:/run/secrets/wp_credentials:ro
    container_name: ftp
    ports:
      - "${FTP_PORT}:${FTP_PORT}"
      - "${FTP_FROM}-${FTP_TO}:${FTP_FROM}-${FTP_TO}"
    networks:
      - inception
    restart: unless-stopped
    depends_on:
      - wordpress

  redis:
    build:
      context: ./requirements/bonus/redis
    container_name: redis
    networks:
      - inception
    expose:
      - ${REDIS_PORT}
    restart: unless-stopped

  uptime-kuma:
    build:
      context: ./requirements/bonus/uptime-kuma
    container_name: uptime-kuma
    expose:
     - ${KUMA_PORT}
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - inception
    restart: unless-stopped

volumes:
  web:
    driver: local
    driver_opts:
      type: none
      device: /home/dcsicsak/data/web
      o: bind

  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/dcsicsak/data/mariadb
      o: bind

  uptime-kuma-data:
    driver: local
    driver_opts:
      type: none
      device: /home/dcsicsak/data/uptime-kuma
      o: bind

networks:
  inception:
    driver: bridge
