services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - PHP_HOST=${PHP_HOST}
      - PHP_PORT=${PHP_PORT}
      - CERTS_CRT=${CERTS_CRT}
      - CERTS_KEY=${CERTS_KEY}
    depends_on:
      - wordpress
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - web:/var/www/html
      - ./secrets/credentials.txt:/run/secrets/wp_credentials:ro
      - ./secrets/db_password.txt:/run/secrets/db_passwords:ro
    environment:
      - WP_EMAIL=${WP_EMAIL}
      - WP_TITLE=${WP_TITLE}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - PHP_HOST=${PHP_HOST}
      - PHP_PORT=${PHP_PORT}
    depends_on:
      - mariadb
    networks:
      - inception
    restart: unless-stopped

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
      - ./secrets/credentials.txt:/run/secrets/wp_credentials:ro
      - ./secrets/db_password.txt:/run/secrets/db_passwords:ro
      - ./secrets/db_root_password.txt:/run/secrets/db_root_password:ro
    networks:
      - inception
    restart: unless-stopped

  static:
    build:
      context: ./requirements/bonus/static
    container_name: static
    volumes:
      - static:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  adminer:
    build:
      context: ./requirements/bonus/adminer
    container_name: adminer
    networks:
      - inception
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  web:
    driver: local
    driver_opts:
      type: none
      device: /home/dcsicsak/data/web
      o: bind

  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/dcsicsak/data/mariadb
      o: bind

  static:
    driver: local
    driver_opts:
      type: none
      device: /home/dcsicsak/data/static
      o: bind

networks:
  inception:
    driver: bridge
