version: "3.8"

services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - web:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - web:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

volumes:
  mariadb_data:
  web:

networks:
  inception:
    driver: bridge
