version: "3.8"

services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - web:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: unless-stopped

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped


volumes:
  web:
    driver: local
    driver_opts:
      type: none
      device: /home/dcsicsak/data/web
      o: bind

  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/dcsicsak/data/mariadb
      o: bind

networks:
  inception:
    driver: bridge
